---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ww-mariadb-pv
  namespace: webwork2
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: "3Gi"
  hostPath:
    path: /mnt/db

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ww-mariadb-pvc
  namespace: webwork2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww-mariadb-deploy
  namespace: webwork2
  labels:
    app: ww-mariadb
    type: ww-database
spec:
  selector:
    matchLabels:
      app: ww-mariadb
      type: ww-database
  replicas: 1
  template:
    metadata:
      name: ww-mariadb-pod
      labels:
        app: ww-mariadb
        type: ww-database
    spec:
      containers:
      - image: hosseinmohammadi/ww2-db:v1.2
        name: ww-mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: YOURPASSWORD
        - name: MYSQL_DATABASE
          value: webwork
        - name: MYSQL_USER
          value: webworkWrite
        ports:
        - containerPort: 3306
          name: ww-mariadb
        volumeMounts:
        - name: ww-mariadb-persistent-storage
          mountPath: /var/lib/mysql
          subPath: "db"
      volumes:
      - name: ww-mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: ww-mariadb-pvc           
---

kind: Service
apiVersion: v1
metadata:
  name: ww-db
  namespace: webwork2
spec:
  selector:
    app: ww-mariadb
  ports:
    - name: wwmariadbportname
      port: 3306
      protocol: TCP
