apiVersion: v1
kind: PersistentVolume
metadata:
  name: ww-pv-course
  namespace: webwork2
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: "3Gi"
  hostPath:
    path: /mnt/courses

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ww-pvc-course
  namespace: webwork2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ww-pv-htdocs
  namespace: webwork2
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: "3Gi"
  hostPath:
    path: /mnt/htdocs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ww-pvc-htdocs
  namespace: webwork2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww-deployment
  namespace: webwork2
  labels:
    app: ww
    type: webwork
spec:
  template:
    metadata:
      name: ww-pod
      labels:
        app: ww
        type: webwork
    spec:
      containers:
      - image: hosseinmohammadi/webwork2:v1.5
        name: ww-pod
        env:
        - name: WEBWORK_DB_HOST
          value: 'ww-db'
        - name: WEBWORK_DB_PORT
          value: '3306'
        - name: WEBWORK_DB_NAME
          value: "webwork"
        - name: WEBWORK_DB_DSN
          value: "DBI:mysql:webwork:ww-db:3306"
        - name: WEBWORK_DB_PASSWORD
          value: "YOURPASSWORD"
        - name: WEBWORK_DB_USER
          value: "webworkWrite"
        - name: WEBWORK_TIMEZONE
          value: "Europe/Istanbul"
        - name: DEV
          value: "0"
        - name: APACHE_RUN_GROUP
          value: "www-data"
        ports:
          - containerPort: 80
            name: ww-port
        volumeMounts:
        - mountPath: "/opt/webwork/courses"
          name: courses
          subPath: "courses"
        - mountPath: "/opt/webwork/webwork2/htdocs/tmp"
          name: htdocs
          subPath: "ww2-htdocs-tmp"
      volumes:
      - name: courses
        persistentVolumeClaim:
          claimName: ww-pvc-course
      - name: htdocs
        persistentVolumeClaim:
          claimName: ww-pvc-htdocs
  replicas: 1
  selector:
    matchLabels:
      app: ww
      type: webwork

---
apiVersion: v1
kind: Service
metadata:
  name: ww-service
  namespace: webwork2
spec:
  selector:
    app: ww
    type: webwork
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31211
  type: NodePort
