apiVersion: v1
kind: Service
metadata:
  name: ww-lb
  namespace: webwork2
spec:
  externalIPs:
  - ***.***.***.*** # YOUR IP ADDRESS
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31200
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ww
    type: webwork
  sessionAffinity: None
  type: LoadBalancer
